/* eslint-disable */
// This file is auto-generated by scripts/generate-whats-new.ts.
// Do not edit this file directly.

import type {
  WhatsNewEntrySource,
  WhatsNewOverviewSource,
} from "./whats-new-types"

export const GENERATED_WHATS_NEW_OVERVIEW = {
  "title": "What's new",
  "description": "A weekly digest for the changes worth posting: the headline, why it matters, and a clean changelog for what shipped.",
  "intro": "This section turns the raw pace of product and docs work into something editorial: one clear weekly digest instead of a stream of scattered updates.",
  "body": "The idea is simple: keep the raw internal changelog as source material, then publish a lighter weekly roundup that turns the most important shipped work into something readable."
} satisfies WhatsNewOverviewSource

export const GENERATED_WHATS_NEW_ENTRIES = [
  {
    "slug": "2026-w15",
    "weekLabel": "Week 15",
    "shortDateRange": "Apr 6-10",
    "fullDateRange": "April 6-10, 2026",
    "publishedAt": "2026-04-10T17:00:00.000Z",
    "focus": "Sandboxes / Runtime / Templates",
    "title": "Sandbox config opens up, and Claude Code runtime moves to ACP",
    "teaser": "Deploy-time CPU and memory, runtime network overrides in the SDKs, and a persistent ACP session for Claude Code in the sandbox.",
    "overviewBody": "Sandbox shape moved out of fixed template defaults: `cpuCount`, `memoryMB`, `timeoutMs`, and the `networkAllowOut`/`networkDenyOut` pair are now set in `agent.config.ts` or overridden per-call in the server SDKs. Claude Code sessions migrated from per-message SDK boot to a persistent ACP path inside the sandbox, so warm follow-ups reuse the same session instead of booting a fresh transformer each turn.",
    "alsoIncludes": [
      "`/agents/new` quickstart wizard (alpha)",
      "`/community/agents` Agent Templates registry",
      "runtime-tagged billing events on relay",
      "mobile action bars on agent pages"
    ],
    "intro": "April 6–10 was an infrastructure week. The sandbox stopped being a fixed artifact and became something you configure at deploy time and per call from your own backend. The Claude Code runtime moved off the legacy per-message SDK path onto a persistent ACP session, and the relay picks its stream transformer from the `streamId` prefix so future runtimes can ship without duplicating the whole integration. On the public side, the Agent Templates registry landed at `/community/agents`.",
    "changes": [
      "Added `cpuCount` and `memoryMB` to `agent.config.ts`, so sandbox size is pinned at deploy time instead of being patched after first boot. Picked up by the CLI bundler and the relay sandbox factory.",
      "Added `timeoutMs`, `networkAllowOut`, and `networkDenyOut` runtime overrides on `SandboxClient.create()` in `@21st-sdk/node` and the Python SDK — each call can narrow TTL and outbound networking without redeploying the agent.",
      "Template-backed files now travel with the deploy artifact: files and values listed in the agent template are baked into the built sandbox instead of being written in after boot.",
      "Moved Claude Code sessions onto a persistent ACP runtime path inside the sandbox. Warm follow-ups reuse the same ACP session instead of booting a fresh transformer each turn; legacy sandboxes keep working through a fallback path.",
      "Relay now selects the stream transformer from the `streamId` prefix, unifying the Claude Code path with whatever runtime ships next.",
      "Billing events emitted by relay are now tagged with `runtime`, so Claude Code usage is separable from other runtimes on the invoice.",
      "Shipped `/agents/new` quickstart wizard (alpha): guided bundle upload and no-code deploy, backed by new `/api/agents/wizard` and `/api/agents/deploy-nocode` routes.",
      "Shipped the Agent Templates registry at `/community/agents`: browse, search, publish, and bookmark. Replaces the earlier \"Community Agents\" naming.",
      "Added category, tag, and MCP-specific discovery pages under `/community/agents`.",
      "Added mobile action bars and improved focus-ring contrast on agent config export buttons."
    ]
  }
] satisfies WhatsNewEntrySource[]
