import fs from "node:fs/promises"
import path from "node:path"
import matter from "gray-matter"
import { z } from "zod"

const APP_ROOT = path.resolve(__dirname, "..")
const CONTENT_DIR = path.join(APP_ROOT, "content", "whats-new")
const OUTPUT_FILE = path.join(
  APP_ROOT,
  "lib",
  "agents-docs",
  "generated-whats-new.ts",
)

const overviewSchema = z.object({
  title: z.string().min(1),
  description: z.string().min(1),
  intro: z.string().min(1),
  body: z.string().min(1),
})

const entrySchema = z.object({
  slug: z.string().regex(/^\d{4}-w\d{1,2}$/),
  weekLabel: z.string().min(1),
  shortDateRange: z.string().min(1),
  fullDateRange: z.string().min(1),
  publishedAt: z.string().datetime({ offset: true }),
  focus: z.string().min(1),
  title: z.string().min(1),
  teaser: z.string().min(1),
  overviewBody: z.string().min(1),
  alsoIncludes: z.array(z.string().min(1)).min(1),
  intro: z.string().min(1),
  changes: z.array(z.string().min(1)).min(1),
})

async function readOverview() {
  const raw = await fs.readFile(path.join(CONTENT_DIR, "index.md"), "utf8")
  const { data } = matter(raw)
  return overviewSchema.parse(data)
}

async function readEntries() {
  const names = await fs.readdir(CONTENT_DIR)
  const entries = await Promise.all(
    names
      .filter((name) => name.endsWith(".md") && name !== "index.md")
      .map(async (name) => {
        const raw = await fs.readFile(path.join(CONTENT_DIR, name), "utf8")
        const { data } = matter(raw)
        return entrySchema.parse(data)
      }),
  )

  return entries.sort(
    (left, right) =>
      new Date(right.publishedAt).getTime() -
      new Date(left.publishedAt).getTime(),
  )
}

function formatGeneratedSource(input: { overview: unknown; entries: unknown }) {
  const overview = JSON.stringify(input.overview, null, 2)
  const entries = JSON.stringify(input.entries, null, 2)

  return `/* eslint-disable */
// This file is auto-generated by scripts/generate-whats-new.ts.
// Do not edit this file directly.

import type {
  WhatsNewEntrySource,
  WhatsNewOverviewSource,
} from "./whats-new-types"

export const GENERATED_WHATS_NEW_OVERVIEW = ${overview} satisfies WhatsNewOverviewSource

export const GENERATED_WHATS_NEW_ENTRIES = ${entries} satisfies WhatsNewEntrySource[]
`
}

async function main() {
  const overview = await readOverview()
  const entries = await readEntries()
  const output = formatGeneratedSource({ overview, entries })

  await fs.writeFile(OUTPUT_FILE, output)

  console.log(
    `Generated ${path.relative(APP_ROOT, OUTPUT_FILE)} from ${entries.length} What's New files.`,
  )
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
