apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: relay-pvc-manager
  namespace: opensandbox
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: relay-pvc-manager
  namespace: opensandbox
subjects:
  - kind: Group
    name: relay-pvc-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: relay-pvc-manager
