const ROUTES = new Set([
  "api",
  "auth",
  "sign-in",
  "sign-up",
  "admin",
  "settings",
  "pricing",
  "checkout",
  "magic",
  "mcp",
  "magic-chat",
  "agents",
  "1code",

  "magic-chat-old",
  "studio",
  "publish",
  "authors",
  "changelog",
  "our-story",
  "vs-code-extension",
  "extension",
  "maintenance",
  "success",
  "toolbar",
  "public-chat",
  "public-dashboard",
  "public-project",
  "api-access",
  "terms",
  "home",
  "community",
  "canvas",
  "canvas-cc",
  "chats",
  "partner-program",
  "r",
  "claim",
  "docs",
  "sdk",
  "waitlist",
  "homepage",
  "invite",
  "diff",
  "integrations",
  "_next",
  "favicon.ico",
  "sitemap.xml",
])

export function isKnownTopLevelRoute(segment: string): boolean {
  return ROUTES.has(segment)
}
